### PR TITLE
apply phpdoc_no_empty_return fixer

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by lode** [comment]
:-1: I would prefer to keep these.

**Comment by bobthecow** [comment]
@lode I'm not sure I agree. What's your reason?

**Comment by lode** [comment]
Sorry for a short / harsh comment from my side. I'd like to see a full doc, with what I can expect. When you see a return void you directly know to not expect anything. Otherwise, you'd have to think about it; "What is the return? Ah nothing, because nothing is stated. Or is it forgotten?"

**Comment by keradus** [comment]
I don't like the dummy info that gives me nothing.

Project is good, docs is good, if sth should be documented, like return, it is.
If sb screw and not write a proper doc then any linting tool he is using will trigger an warning on it.
Make a standards good for good developers, not to carry about "what if dev screw up"

**Comment by bobthecow** [comment]
@lode In my experience, it's far more common to incorrectly have `@return void` or `@return null` because either a function used to return that, or someone's IDE automatically wrote that and nobody bothered to fix it :)

**Comment by bobthecow** [comment]
Either way, this project currently follows the Symfony style guide, which says to omit them.

**Comment by lode** [comment]
Good point @bobthecow.

**Pull request merged**
